--------------------------------------------------------
--  Constraints for Table MAK_72_APPROVEABLE_PA_TABLE
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_72_APPROVEABLE_PA_TABLE" MODIFY ("SCHEDARRIVDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_72_APPROVEABLE_PA_TABLE" MODIFY ("SCHEDSHIPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_72_APPROVEABLE_PA_TABLE" MODIFY ("OHPOST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_72_APPROVEABLE_PA_TABLE" MODIFY ("FCSTADJRULE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_72_APPROVEABLE_PA_TABLE" MODIFY ("SOURCING" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_72_APPROVEABLE_PA_TABLE" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_72_APPROVEABLE_PA_TABLE" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_72_APPROVEABLE_PA_TABLE" MODIFY ("ITEM" NOT NULL ENABLE)
