--------------------------------------------------------
--  Constraints for Table MAK_TEST_P1_COST_SHIFT2
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_TEST_P1_COST_SHIFT2" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_TEST_P1_COST_SHIFT2" MODIFY ("COST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_TEST_P1_COST_SHIFT2" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_TEST_P1_COST_SHIFT2" MODIFY ("SOURCE" NOT NULL ENABLE)
