--------------------------------------------------------
--  DDL for Table MAK_CUST_TABLE
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."MAK_CUST_TABLE" 
   (	"STATUS" NUMBER DEFAULT 0, 
	"SM_RECORD" NUMBER, 
	"CO_ITEM" VARCHAR2(50 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"SHIPDATE" DATE, 
	"SCHEDSHIPDATE" DATE, 
	"SCHEDARRIVDATE" DATE, 
	"CO_ORDERID" VARCHAR2(50 CHAR), 
	"CO_QTY" FLOAT(126), 
	"U_SALES_DOCUMENT" VARCHAR2(10 CHAR), 
	"U_SHIP_CONDITION" VARCHAR2(10 CHAR), 
	"U_DMDGROUP_CODE" VARCHAR2(10 CHAR), 
	"VL_ORDERID" NUMBER(*,0), 
	"LOADID" VARCHAR2(50 CHAR), 
	"VLL_DEST" VARCHAR2(50 CHAR), 
	"VLL_SOURCE" VARCHAR2(50 CHAR), 
	"VLL_QTY" FLOAT(126), 
	"VLL_ITEM" VARCHAR2(50 CHAR), 
	"ASSIGNED_PLANT" VARCHAR2(10), 
	"U_OVERALLSTS" VARCHAR2(10), 
	"P1" NUMBER DEFAULT 0, 
	"FIRMSW" NUMBER DEFAULT 0, 
	"SM417_RECNUM" NUMBER DEFAULT 0, 
	"SM417_EFF" DATE, 
	"SOURCING" VARCHAR2(50) DEFAULT ' ', 
	"MINLEADTIME" NUMBER DEFAULT -1, 
	"DUR" NUMBER DEFAULT 0, 
	"U_RATE_TYPE" VARCHAR2(20) DEFAULT ' '
   ) 

   COMMENT ON COLUMN "SCPOMGR"."MAK_CUST_TABLE"."FIRMSW" IS 'This column will have a value of 1 for records that we want to return to SAP.'
   COMMENT ON COLUMN "SCPOMGR"."MAK_CUST_TABLE"."U_RATE_TYPE" IS 'From the UDT_COST_TRANSIT TABLE.'
