--------------------------------------------------------
--  DDL for Table MAK_60_PLANNARRIV_NA_TABLE
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."MAK_60_PLANNARRIV_NA_TABLE" 
   (	"ITEM" VARCHAR2(50 CHAR), 
	"DEST" VARCHAR2(50 CHAR), 
	"DESCR" VARCHAR2(50 CHAR), 
	"CITY" VARCHAR2(50 CHAR), 
	"STATE" VARCHAR2(50 CHAR), 
	"POSTALCODE" VARCHAR2(10 CHAR), 
	"U_CUSTORDERID" VARCHAR2(50 CHAR), 
	"LOADID" VARCHAR2(50 CHAR), 
	"SOURCE" VARCHAR2(50 CHAR), 
	"DESCR_SOURCE" VARCHAR2(50 CHAR), 
	"CITY_SOURCE" VARCHAR2(50 CHAR), 
	"STATE_SOURCE" VARCHAR2(50 CHAR), 
	"PC_SOURCE" VARCHAR2(10 CHAR), 
	"SOURCING" VARCHAR2(50 CHAR), 
	"RPA" VARCHAR2(50 CHAR), 
	"TRANSIT_TIME" NUMBER, 
	"SCHEDSHIPDATE" DATE, 
	"SCHEDARRIVDATE" DATE, 
	"QTY" NUMBER
   )
