--------------------------------------------------------
--  Constraints for Table MAK_CUST_TABLE_BKUP
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_CUST_TABLE_BKUP" MODIFY ("P1" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_CUST_TABLE_BKUP" MODIFY ("CO_QTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_CUST_TABLE_BKUP" MODIFY ("CO_ORDERID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_CUST_TABLE_BKUP" MODIFY ("SHIPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_CUST_TABLE_BKUP" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_CUST_TABLE_BKUP" MODIFY ("CO_ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_CUST_TABLE_BKUP" MODIFY ("SM_RECORD" NOT NULL ENABLE)
