--------------------------------------------------------
--  Constraints for Table MAK_VLL_TABLE
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_VLL_TABLE" MODIFY ("SRCNG_AR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_VLL_TABLE" MODIFY ("SRCNG_SR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_VLL_TABLE" MODIFY ("SFF_AR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_VLL_TABLE" MODIFY ("EFF_SR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_VLL_TABLE" MODIFY ("ORDERID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_VLL_TABLE" MODIFY ("QTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_VLL_TABLE" MODIFY ("SCHEDARRIVDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_VLL_TABLE" MODIFY ("SCHEDSHIPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_VLL_TABLE" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_VLL_TABLE" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_VLL_TABLE" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_VLL_TABLE" MODIFY ("LOADID" NOT NULL ENABLE)
