--------------------------------------------------------
--  DDL for Table MAK_VEHICLELOADLINE_BK0227
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."MAK_VEHICLELOADLINE_BK0227" 
   (	"LOADID" VARCHAR2(50 CHAR), 
	"ITEM" VARCHAR2(50 CHAR), 
	"QTY" FLOAT(126), 
	"SUPPLYMETHOD" FLOAT(126), 
	"LOADLINEID" FLOAT(126), 
	"CANCELSW" NUMBER, 
	"REVISEDDATE" DATE, 
	"ACTIONALLOWEDSW" NUMBER, 
	"PRIMARYITEM" VARCHAR2(50 CHAR), 
	"DRAWQTY" FLOAT(126), 
	"EXPDATE" DATE, 
	"ACTION" NUMBER(*,0), 
	"ACTIONDATE" DATE, 
	"ACTIONQTY" FLOAT(126), 
	"ORDERNUM" NUMBER(*,0), 
	"FF_TRIGGER_CONTROL" NUMBER(*,0), 
	"SOURCING" VARCHAR2(50 CHAR), 
	"MUSTGOQTY" NUMBER(38,0), 
	"SEQNUM" NUMBER(*,0), 
	"SCHEDSHIPDATE" DATE, 
	"SCHEDARRIVDATE" DATE, 
	"LBSOURCE" NUMBER, 
	"ORDERID" NUMBER(*,0), 
	"SUPPORDERQTY" FLOAT(126), 
	"REVISEDEXPDATE" DATE, 
	"SOURCE" VARCHAR2(50 CHAR), 
	"DEST" VARCHAR2(50 CHAR), 
	"GROUPORDERID" NUMBER(*,0), 
	"PRIMARYITEMQTY" FLOAT(126), 
	"SUPPLYID" VARCHAR2(50 CHAR), 
	"U_OVERALLSTS" VARCHAR2(1 CHAR)
   )
