--------------------------------------------------------
--  Constraints for Table MAK_RESPENALTY2
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_RESPENALTY2" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_RESPENALTY2" MODIFY ("TIMEUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_RESPENALTY2" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_RESPENALTY2" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_RESPENALTY2" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_RESPENALTY2" MODIFY ("RATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_RESPENALTY2" MODIFY ("EFF" NOT NULL ENABLE)
