--------------------------------------------------------
--  Constraints for Table MAK_RESPENALTY
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_RESPENALTY" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_RESPENALTY" MODIFY ("TIMEUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_RESPENALTY" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_RESPENALTY" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_RESPENALTY" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_RESPENALTY" MODIFY ("RATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_RESPENALTY" MODIFY ("EFF" NOT NULL ENABLE)
