--------------------------------------------------------
--  Constraints for Table MAK_MISSING_GIDLINIT_RECS
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_MISSING_GIDLINIT_RECS" MODIFY ("U_LOC_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_MISSING_GIDLINIT_RECS" MODIFY ("PRIMARY_KEY_COL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_MISSING_GIDLINIT_RECS" MODIFY ("LOC" NOT NULL ENABLE)
