--------------------------------------------------------
--  DDL for Table MAK_CUST_TABLE_BKUP
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."MAK_CUST_TABLE_BKUP" 
   (	"STATUS" NUMBER, 
	"SM_RECORD" NUMBER, 
	"CO_ITEM" VARCHAR2(50 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"SHIPDATE" DATE, 
	"SCHEDSHIPDATE" DATE, 
	"SCHEDARRIVDATE" DATE, 
	"CO_ORDERID" VARCHAR2(50 CHAR), 
	"CO_QTY" FLOAT(126), 
	"U_SALES_DOCUMENT" VARCHAR2(10 CHAR), 
	"U_SHIP_CONDITION" VARCHAR2(10 CHAR), 
	"U_DMDGROUP_CODE" VARCHAR2(10 CHAR), 
	"VL_ORDERID" NUMBER(*,0), 
	"LOADID" VARCHAR2(50 CHAR), 
	"VLL_DEST" VARCHAR2(50 CHAR), 
	"VLL_SOURCE" VARCHAR2(50 CHAR), 
	"VLL_QTY" FLOAT(126), 
	"VLL_ITEM" VARCHAR2(50 CHAR), 
	"ASSIGNED_PLANT" VARCHAR2(10), 
	"U_OVERALLSTS" VARCHAR2(10), 
	"P1" NUMBER, 
	"FIRMSW" NUMBER, 
	"SM417_RECNUM" NUMBER, 
	"SM417_EFF" DATE, 
	"SOURCING" VARCHAR2(50)
   )
