--------------------------------------------------------
--  Constraints for Table MAK_COST_TRANSIT_NA
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_COST_TRANSIT_NA" MODIFY ("LANE_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COST_TRANSIT_NA" MODIFY ("U_EQUIPMENT_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COST_TRANSIT_NA" MODIFY ("DEST_GEO" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COST_TRANSIT_NA" MODIFY ("SOURCE_GEO" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COST_TRANSIT_NA" MODIFY ("DISTANCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COST_TRANSIT_NA" MODIFY ("COST_PALLET" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COST_TRANSIT_NA" MODIFY ("COST_KM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COST_TRANSIT_NA" MODIFY ("TRANSITTIME" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COST_TRANSIT_NA" MODIFY ("SALESGROUP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COST_TRANSIT_NA" MODIFY ("DEST_PC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COST_TRANSIT_NA" MODIFY ("DEST_CO" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COST_TRANSIT_NA" MODIFY ("SOURCE_PC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COST_TRANSIT_NA" MODIFY ("SOURCE_CO" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COST_TRANSIT_NA" MODIFY ("DIRECTION" NOT NULL ENABLE)
