--------------------------------------------------------
--  Constraints for Table MAK_SM_417_TABLE
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_SM_417_TABLE" MODIFY ("P1" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SM_417_TABLE" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SM_417_TABLE" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SM_417_TABLE" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SM_417_TABLE" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SM_417_TABLE" MODIFY ("RECNUM" NOT NULL ENABLE)
