--------------------------------------------------------
--  Constraints for Table MAK_SM_TABLE_BKUP
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_SM_TABLE_BKUP" MODIFY ("P1" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SM_TABLE_BKUP" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SM_TABLE_BKUP" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SM_TABLE_BKUP" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SM_TABLE_BKUP" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SM_TABLE_BKUP" MODIFY ("RECNUM" NOT NULL ENABLE)
