--------------------------------------------------------
--  Constraints for Table MAK_UDT_PLANARRIV_EXTRACT_BK
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_UDT_PLANARRIV_EXTRACT_BK" MODIFY ("SOURCING" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_UDT_PLANARRIV_EXTRACT_BK" MODIFY ("SCHEDSHIPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_UDT_PLANARRIV_EXTRACT_BK" MODIFY ("NEEDSHIPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_UDT_PLANARRIV_EXTRACT_BK" MODIFY ("SCHEDARRIVDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_UDT_PLANARRIV_EXTRACT_BK" MODIFY ("NEEDARRIVDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_UDT_PLANARRIV_EXTRACT_BK" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_UDT_PLANARRIV_EXTRACT_BK" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_UDT_PLANARRIV_EXTRACT_BK" MODIFY ("ITEM" NOT NULL ENABLE)
