--------------------------------------------------------
--  Constraints for Table MAK_CUST_TABLE
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_CUST_TABLE" MODIFY ("P1" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_CUST_TABLE" MODIFY ("CO_ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_CUST_TABLE" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_CUST_TABLE" MODIFY ("SHIPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_CUST_TABLE" MODIFY ("CO_ORDERID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_CUST_TABLE" MODIFY ("CO_QTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_CUST_TABLE" MODIFY ("SM_RECORD" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_CUST_TABLE" ADD CONSTRAINT "MAK_CUST_TABLE_PK" PRIMARY KEY ("CO_ORDERID")
  USING INDEX  ENABLE
