--------------------------------------------------------
--  Constraints for Table MAK_COSTTIER_TABLE_BKUP
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_COSTTIER_TABLE_BKUP" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COSTTIER_TABLE_BKUP" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COSTTIER_TABLE_BKUP" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COSTTIER_TABLE_BKUP" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COSTTIER_TABLE_BKUP" MODIFY ("COST" NOT NULL ENABLE)
