--------------------------------------------------------
--  Constraints for Table MAK_COSTTIER_TABLE
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_COSTTIER_TABLE" ADD CONSTRAINT "MAK_COSTTIER_TABLE_PK" PRIMARY KEY ("COST")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."MAK_COSTTIER_TABLE" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COSTTIER_TABLE" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COSTTIER_TABLE" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COSTTIER_TABLE" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_COSTTIER_TABLE" MODIFY ("COST" NOT NULL ENABLE)
