--------------------------------------------------------
--  Constraints for Table MAK_TEST_P1_COST_SHIFT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_TEST_P1_COST_SHIFT" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_TEST_P1_COST_SHIFT" MODIFY ("COST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_TEST_P1_COST_SHIFT" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_TEST_P1_COST_SHIFT" MODIFY ("SOURCE" NOT NULL ENABLE)
