--------------------------------------------------------
--  Constraints for Table MAK_60_PLANNARRIV_NA_TABLE
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_60_PLANNARRIV_NA_TABLE" MODIFY ("SCHEDARRIVDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_60_PLANNARRIV_NA_TABLE" MODIFY ("SCHEDSHIPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_60_PLANNARRIV_NA_TABLE" MODIFY ("SOURCING" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_60_PLANNARRIV_NA_TABLE" MODIFY ("STATE_SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_60_PLANNARRIV_NA_TABLE" MODIFY ("CITY_SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_60_PLANNARRIV_NA_TABLE" MODIFY ("DESCR_SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_60_PLANNARRIV_NA_TABLE" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_60_PLANNARRIV_NA_TABLE" MODIFY ("STATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_60_PLANNARRIV_NA_TABLE" MODIFY ("CITY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_60_PLANNARRIV_NA_TABLE" MODIFY ("DESCR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_60_PLANNARRIV_NA_TABLE" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_60_PLANNARRIV_NA_TABLE" MODIFY ("ITEM" NOT NULL ENABLE)
