--------------------------------------------------------
--  DDL for Table MAK_72_APPROVEABLE_PA_TABLE
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."MAK_72_APPROVEABLE_PA_TABLE" 
   (	"ITEM" VARCHAR2(50 CHAR), 
	"DEST" VARCHAR2(50 CHAR), 
	"SOURCE" VARCHAR2(50 CHAR), 
	"SOURCING" VARCHAR2(50 CHAR), 
	"U_CUSTORDERID" VARCHAR2(50 CHAR), 
	"LOADID" VARCHAR2(50 CHAR), 
	"FCSTADJRULE" NUMBER(*,0), 
	"COD" NUMBER, 
	"OHPOST" DATE, 
	"LT" NUMBER, 
	"SCHEDSHIPDATE" DATE, 
	"SCHEDARRIVDATE" DATE, 
	"QTY" NUMBER, 
	"CO_AVG_QTY" NUMBER, 
	"CO_CNT" NUMBER, 
	"CO_QTY" NUMBER, 
	"CHK_QTY" NUMBER, 
	"CHK_INT" NUMBER, 
	"CHK_LT" NUMBER, 
	"CHK" NUMBER
   )
