--------------------------------------------------------
--  Constraints for Table MAK_SM_TABLE
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_SM_TABLE" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SM_TABLE" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SM_TABLE" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SM_TABLE" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SM_TABLE" ADD CONSTRAINT "MAK_SM_TABLE_PK" PRIMARY KEY ("RECNUM")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."MAK_SM_TABLE" MODIFY ("RECNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SM_TABLE" MODIFY ("P1" NOT NULL ENABLE)
