--------------------------------------------------------
--  Constraints for Table MAK_SOURCINGMETRIC
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_SOURCINGMETRIC" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SOURCINGMETRIC" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SOURCINGMETRIC" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SOURCINGMETRIC" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SOURCINGMETRIC" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SOURCINGMETRIC" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SOURCINGMETRIC" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SOURCINGMETRIC" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SOURCINGMETRIC" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SOURCINGMETRIC" MODIFY ("SOURCING" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SOURCINGMETRIC" ADD CONSTRAINT "MAK_SOURCINGMETRIC_CHK1" CHECK (DUR >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."MAK_SOURCINGMETRIC" ADD CONSTRAINT "MAK_SOURCINGMETRIC_PK" PRIMARY KEY ("SOURCING", "ITEM", "DEST", "SOURCE", "EFF", "CATEGORY")
  USING INDEX  ENABLE
