--------------------------------------------------------
--  Constraints for Table MAK_SKUCONSTRAINT_BKUP
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_SKUCONSTRAINT_BKUP" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SKUCONSTRAINT_BKUP" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SKUCONSTRAINT_BKUP" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SKUCONSTRAINT_BKUP" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SKUCONSTRAINT_BKUP" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SKUCONSTRAINT_BKUP" MODIFY ("QTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SKUCONSTRAINT_BKUP" MODIFY ("POLICY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SKUCONSTRAINT_BKUP" MODIFY ("EFF" NOT NULL ENABLE)
