--------------------------------------------------------
--  Constraints for Table PENALTYCATEGORY
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PENALTYCATEGORY" ADD CONSTRAINT "BOOL_PENALTYCATG_SKUSW" CHECK (SKUSw IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."PENALTYCATEGORY" ADD CONSTRAINT "BOOL_PENALTYCATG_RESSW" CHECK (ResSw IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."PENALTYCATEGORY" ADD CONSTRAINT "BOOL_PENALTYCATG_PRODUCTIONSW" CHECK (ProductionSw IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."PENALTYCATEGORY" ADD CONSTRAINT "BOOL_PENALTYCATG_SOURCINGSW" CHECK (SourcingSw IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."PENALTYCATEGORY" ADD CONSTRAINT "XPKPENALTYCATEGORY" PRIMARY KEY ("CATEGORY")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."PENALTYCATEGORY" MODIFY ("PERUOMCATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PENALTYCATEGORY" MODIFY ("UOMCATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PENALTYCATEGORY" MODIFY ("SOURCINGSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PENALTYCATEGORY" MODIFY ("PRODUCTIONSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PENALTYCATEGORY" MODIFY ("RESSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PENALTYCATEGORY" MODIFY ("SKUSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PENALTYCATEGORY" MODIFY ("RESKEY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PENALTYCATEGORY" MODIFY ("DESCR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PENALTYCATEGORY" MODIFY ("CATEGORY" NOT NULL ENABLE)
