--------------------------------------------------------
--  Constraints for Table PLANARRIV
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("U_SENT" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" ADD CONSTRAINT "BOOL_PLANARRIV_FIRMPLANSW" CHECK (FIRMPLANSW IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."PLANARRIV" ADD CONSTRAINT "PERCENTAGE4" CHECK (ShrinkageFactor BETWEEN 0.0 AND 100.0) ENABLE
  ALTER TABLE "SCPOMGR"."PLANARRIV" ADD CONSTRAINT "MPACTIONS3" CHECK (Action IN (0, 1, 2, 3)) ENABLE
  ALTER TABLE "SCPOMGR"."PLANARRIV" ADD CONSTRAINT "BOOL_PLANARRIV_ACTIONALOWEDSW" CHECK (ActionAllowedSw IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."PLANARRIV" ADD CONSTRAINT "PLANARRIV_PK" PRIMARY KEY ("ITEM", "DEST", "SEQNUM")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("U_ADMINDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("NONIGNORABLEQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("REVISEDEXPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("SUPPORDERQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("ORDERPLACEDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("DELIVERYDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("DEPARTUREDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("COVDURSCHEDDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("HEADERSEQNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("SUBSTQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("AVAILTOSHIPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("TRANSMODE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("REVISEDDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("ACTIONQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("ACTIONALLOWEDSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("ACTIONDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("ACTION" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("TRANSNAME" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("SHRINKAGEFACTOR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("SOURCING" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("SEQNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("EXPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("QTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("SCHEDSHIPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("NEEDSHIPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("SCHEDARRIVDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("NEEDARRIVDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("FIRMPLANSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PLANARRIV" MODIFY ("ITEM" NOT NULL ENABLE)
