--------------------------------------------------------
--  DDL for Table PLANARRIV
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."PLANARRIV" 
   (	"ITEM" VARCHAR2(50 CHAR), 
	"DEST" VARCHAR2(50 CHAR), 
	"FIRMPLANSW" NUMBER(1,0) DEFAULT 0, 
	"NEEDARRIVDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"SCHEDARRIVDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"NEEDSHIPDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"SCHEDSHIPDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"QTY" FLOAT(126) DEFAULT 0, 
	"EXPDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"SEQNUM" NUMBER(*,0), 
	"SOURCING" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"SHRINKAGEFACTOR" NUMBER(*,0) DEFAULT 0, 
	"TRANSNAME" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"SOURCE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"ACTION" NUMBER(*,0) DEFAULT 0, 
	"ACTIONDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"ACTIONALLOWEDSW" NUMBER(1,0) DEFAULT 0, 
	"ACTIONQTY" FLOAT(126) DEFAULT 0, 
	"REVISEDDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"TRANSMODE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"AVAILTOSHIPDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"SUBSTQTY" FLOAT(126) DEFAULT 0, 
	"FF_TRIGGER_CONTROL" NUMBER(*,0), 
	"HEADERSEQNUM" NUMBER(*,0) DEFAULT 0, 
	"COVDURSCHEDDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"DEPARTUREDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"DELIVERYDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"ORDERPLACEDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"SUPPORDERQTY" FLOAT(126) DEFAULT 0, 
	"REVISEDEXPDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"NONIGNORABLEQTY" FLOAT(126) DEFAULT 0, 
	"U_ADMINDATE" DATE DEFAULT TO_DATE('01/01/1970', 'MM/dd/yyyy'), 
	"U_Z1BANUM" VARCHAR2(50 CHAR), 
	"U_CUSTORDERID" VARCHAR2(50 CHAR), 
	"U_COMMENT" VARCHAR2(256 CHAR), 
	"U_DP_DEFPLANT" VARCHAR2(50 CHAR), 
	"U_ORDERITEM" NUMBER(22,0), 
	"U_ORDERNUM" NUMBER(22,0) DEFAULT null, 
	"U_REASON" VARCHAR2(50 CHAR), 
	"U_SALES_DOCUMENT" VARCHAR2(4 CHAR), 
	"U_SAP_DEFPLANT" VARCHAR2(50 CHAR), 
	"U_SENT" NUMBER(1,0) DEFAULT 0, 
	"U_SHIP_CONDITION" VARCHAR2(2 CHAR), 
	"U_GIDLIMIT" VARCHAR2(50 CHAR), 
	"U_TEU" NUMBER(22,2), 
	"U_MIXED_SW" NUMBER(*,0), 
	"U_PARTIAL_SW" NUMBER(*,0), 
	"U_LRO" VARCHAR2(50 CHAR), 
	"U_CUSTORDER_ITEM" VARCHAR2(50 CHAR), 
	"U_LOADID" VARCHAR2(50 CHAR) DEFAULT '0'
   ) 

   COMMENT ON COLUMN "SCPOMGR"."PLANARRIV"."ITEM" IS ' '
   COMMENT ON COLUMN "SCPOMGR"."PLANARRIV"."DEPARTUREDATE" IS 'date when planarrival can actually leave the source location ( SchedShipDate +LoadTime) calendarized by WorkingCal'
   COMMENT ON COLUMN "SCPOMGR"."PLANARRIV"."DELIVERYDATE" IS 'date when Planarrival can actually reach the destination location (departuredate + transleadtime) calendarized by TransCal'
   COMMENT ON COLUMN "SCPOMGR"."PLANARRIV"."ORDERPLACEDATE" IS 'SchedShipDate calendarized by ReviewCal'
