--------------------------------------------------------
--  Ref Constraints for Table UDT_LLAMASOFT_DATA
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA" ADD CONSTRAINT "UDT_LLAMASOFT_DATA_LOC_FK1" FOREIGN KEY ("SOURCE")
	  REFERENCES "SCPOMGR"."LOC" ("LOC") ENABLE
  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA" ADD CONSTRAINT "UDT_LLAMASOFT_DATA_LOC_FK2" FOREIGN KEY ("DEST")
	  REFERENCES "SCPOMGR"."LOC" ("LOC") ENABLE
  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA" ADD CONSTRAINT "UDT_LLAMASOFT_DATA_UDT_EQ_FK1" FOREIGN KEY ("U_EQUIPMENT_TYPE")
	  REFERENCES "SCPOMGR"."UDT_EQUIPMENT_TYPE" ("U_EQUIPMENT_TYPE") ENABLE
