--------------------------------------------------------
--  Constraints for Table UDT_RESMETRIC_DY
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_DY" MODIFY ("SETUP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_DY" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_DY" MODIFY ("TIMEUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_DY" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_DY" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_DY" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_DY" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_DY" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_DY" MODIFY ("EFF" NOT NULL ENABLE)
