--------------------------------------------------------
--  Constraints for Table UDT_COSTTIER_P1_ADJUSTMENTS
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_COSTTIER_P1_ADJUSTMENTS" ADD CONSTRAINT "UDT_COSTTIER_P1_ADJUSTMEN_PK" PRIMARY KEY ("COST")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_COSTTIER_P1_ADJUSTMENTS" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COSTTIER_P1_ADJUSTMENTS" MODIFY ("COST" NOT NULL ENABLE)
