--------------------------------------------------------
--  Constraints for Table UDT_LLAMASOFT_DATA_BKUP
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA_BKUP" MODIFY ("U_EQUIPMENT_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA_BKUP" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA_BKUP" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA_BKUP" MODIFY ("ITEM" NOT NULL ENABLE)
