--------------------------------------------------------
--  DDL for Table UDT_IGPERROR_HIST
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_IGPERROR_HIST" 
   (	"RUN_DATE" DATE, 
	"BOM" NUMBER, 
	"CAL" NUMBER, 
	"CALDATA" NUMBER, 
	"COST" NUMBER, 
	"COSTTIER" NUMBER, 
	"CUSTORDER" NUMBER, 
	"LOC" NUMBER, 
	"PRODMETHOD" NUMBER, 
	"PRODUCTIONSTEP" NUMBER, 
	"PRODYIELD" NUMBER, 
	"RES" NUMBER, 
	"RESCONSTRAINT" NUMBER, 
	"RESCOST" NUMBER, 
	"RESPENALTY" NUMBER, 
	"SKU" NUMBER, 
	"SKUDEMANDPARAM" NUMBER, 
	"SKUDEPLOYPARAM" NUMBER, 
	"SKUSSPARAM" NUMBER, 
	"SKUPLANNPARAM" NUMBER, 
	"SKUPENALTY" NUMBER, 
	"SOURCING" NUMBER, 
	"SOURCINGMETRIC" NUMBER, 
	"STORAGEREQ" NUMBER, 
	"VEHICLELOADLINE" NUMBER
   )
