--------------------------------------------------------
--  Constraints for Table UDT_SKUCONSTRAINT_TEMP
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_SKUCONSTRAINT_TEMP" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUCONSTRAINT_TEMP" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUCONSTRAINT_TEMP" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUCONSTRAINT_TEMP" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUCONSTRAINT_TEMP" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUCONSTRAINT_TEMP" MODIFY ("QTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUCONSTRAINT_TEMP" MODIFY ("POLICY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUCONSTRAINT_TEMP" MODIFY ("EFF" NOT NULL ENABLE)
