--------------------------------------------------------
--  Constraints for Table UDT_PLANARRIV_EXTRACT_BKUP
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT_BKUP" MODIFY ("SOURCING" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT_BKUP" MODIFY ("SCHEDSHIPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT_BKUP" MODIFY ("NEEDSHIPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT_BKUP" MODIFY ("SCHEDARRIVDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT_BKUP" MODIFY ("NEEDARRIVDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT_BKUP" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT_BKUP" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT_BKUP" MODIFY ("ITEM" NOT NULL ENABLE)
