--------------------------------------------------------
--  DDL for Table UDT_LLAMASOFT_DATA
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA" 
   (	"ITEM" VARCHAR2(20), 
	"SOURCE" VARCHAR2(50), 
	"SOURCE_PC" VARCHAR2(10), 
	"DEST" VARCHAR2(50), 
	"DEST_PC" VARCHAR2(10), 
	"TRANSLEADTIME" NUMBER, 
	"PRIORITY" NUMBER, 
	"U_EQUIPMENT_TYPE" VARCHAR2(20) DEFAULT 'X', 
	"HASDEMAND" NUMBER(1,0) DEFAULT 0, 
	"HASLANE" NUMBER(1,0) DEFAULT 0, 
	"COSTTRANSITRANK" NUMBER, 
	"COSTTIERRANK" NUMBER DEFAULT NULL
   )
