--------------------------------------------------------
--  Constraints for Table UDT_LLAMASOFT_DATA
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA" ADD CONSTRAINT "UDT_LAMMASOFT_DATA_PK" PRIMARY KEY ("ITEM", "SOURCE", "DEST", "U_EQUIPMENT_TYPE")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA" MODIFY ("U_EQUIPMENT_TYPE" NOT NULL DISABLE)
  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA" MODIFY ("ITEM" NOT NULL ENABLE)
