--------------------------------------------------------
--  Constraints for Table UDT_PRODUCTIONRESMETRIC_DY
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_DY" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_DY" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_DY" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_DY" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_DY" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_DY" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_DY" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_DY" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_DY" MODIFY ("PRODUCTIONMETHOD" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_DY" MODIFY ("QTYUOM" NOT NULL ENABLE)
