--------------------------------------------------------
--  Constraints for Table UDT_PLANARRIV_EXTRACT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT" MODIFY ("SOURCING" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT" MODIFY ("SCHEDSHIPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT" MODIFY ("NEEDSHIPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT" MODIFY ("SCHEDARRIVDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT" MODIFY ("NEEDARRIVDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANARRIV_EXTRACT" MODIFY ("ITEM" NOT NULL ENABLE)
