--------------------------------------------------------
--  Constraints for Table UDT_SKUMETRIC_DY
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_DY" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_DY" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_DY" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_DY" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_DY" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_DY" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_DY" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_DY" MODIFY ("EFF" NOT NULL ENABLE)
