--------------------------------------------------------
--  Constraints for Table UDT_YIELD_NA
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" MODIFY ("DND" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" MODIFY ("YIELD" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" MODIFY ("MINCAP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" MODIFY ("MAXCAP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" MODIFY ("MINDAYSPERWK" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" MODIFY ("MAXDAYSPERWK" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" MODIFY ("MINHRSPERDAY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" MODIFY ("MAXHRSPERDAY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" MODIFY ("EFFICIENCY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" MODIFY ("PRODUCTIONMETHOD" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" MODIFY ("QB" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" MODIFY ("MATCODE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" ADD CONSTRAINT "UDT_YIELD_NA_CHK4" CHECK (MINHRSPERDAY <= MAXHRSPERDAY AND MINDAYSPERWK <= MAXDAYSPERWK) ENABLE
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" ADD CONSTRAINT "UDT_YIELD_NA_CHK3" CHECK (MINCAP <= MAXCAP) ENABLE
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" ADD CONSTRAINT "UDT_YIELD_NA_CHK2" CHECK (DND IN (1, 0)) ENABLE
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" ADD CONSTRAINT "UDT_YIELD_NA_CHK1" CHECK (EFFICIENCY > 0) ENABLE
  ALTER TABLE "SCPOMGR"."UDT_YIELD_NA" ADD CONSTRAINT "UDT_YIELD_NA_PK" PRIMARY KEY ("LOC", "ITEM", "PRODUCTIONMETHOD")
  USING INDEX  ENABLE
