--------------------------------------------------------
--  DDL for Table VEHICLELOADLINE
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."VEHICLELOADLINE" 
   (	"LOADID" VARCHAR2(50 CHAR), 
	"ITEM" VARCHAR2(50 CHAR), 
	"QTY" FLOAT(126) DEFAULT 0, 
	"SUPPLYMETHOD" FLOAT(126) DEFAULT 0.0, 
	"LOADLINEID" FLOAT(126) DEFAULT 0, 
	"CANCELSW" NUMBER DEFAULT 0, 
	"REVISEDDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"ACTIONALLOWEDSW" NUMBER DEFAULT 0, 
	"PRIMARYITEM" VARCHAR2(50 CHAR), 
	"DRAWQTY" FLOAT(126) DEFAULT 1.0, 
	"EXPDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"ACTION" NUMBER(*,0) DEFAULT 0, 
	"ACTIONDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"ACTIONQTY" FLOAT(126) DEFAULT 0, 
	"ORDERNUM" NUMBER(*,0) DEFAULT 0, 
	"FF_TRIGGER_CONTROL" NUMBER(*,0), 
	"SOURCING" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"MUSTGOQTY" NUMBER(38,0) DEFAULT 0, 
	"SEQNUM" NUMBER(*,0) DEFAULT 0, 
	"SCHEDSHIPDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"SCHEDARRIVDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"LBSOURCE" NUMBER DEFAULT 1, 
	"ORDERID" NUMBER(*,0) DEFAULT 0, 
	"SUPPORDERQTY" FLOAT(126) DEFAULT 0, 
	"REVISEDEXPDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"SOURCE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"DEST" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"GROUPORDERID" NUMBER(*,0) DEFAULT 0, 
	"PRIMARYITEMQTY" FLOAT(126) DEFAULT 0, 
	"SUPPLYID" VARCHAR2(50 CHAR), 
	"U_OVERALLSTS" VARCHAR2(1 CHAR)
   ) 

   COMMENT ON COLUMN "SCPOMGR"."VEHICLELOADLINE"."LOADID" IS ' '
