--------------------------------------------------------
--  DDL for Table VEHICLELOAD
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."VEHICLELOAD" 
   (	"LOADID" VARCHAR2(50 CHAR), 
	"DESCR" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"SHIPDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"ARRIVDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"SOURCESTATUS" NUMBER DEFAULT 1, 
	"DESTSTATUS" NUMBER DEFAULT 1, 
	"LBSTATUS" NUMBER DEFAULT 0, 
	"STATUSDESC" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"APPROVALSTATUS" NUMBER(1,0) DEFAULT 0, 
	"EXPORTED" NUMBER(1,0) DEFAULT 0, 
	"UPDATED" NUMBER(1,0) DEFAULT 0, 
	"LBSOURCE" NUMBER DEFAULT 1, 
	"TRANSMODE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"FF_TRIGGER_CONTROL" NUMBER(*,0), 
	"STATUSDESCR" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"LOADSW" NUMBER(1,0) DEFAULT 1, 
	"VENDORMINMETSW" NUMBER(1,0) DEFAULT 0, 
	"TRANSMODEMINMETSW" NUMBER(1,0) DEFAULT 0, 
	"TOLERANCECAPMETSW" NUMBER(1,0) DEFAULT 0, 
	"LANEGROUPMINMETSW" NUMBER(1,0) DEFAULT 0, 
	"CONSOLIDATEDLOADSEQNUM" NUMBER(*,0) DEFAULT 0, 
	"LANEGROUPID" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"MAXCAPACITYMETSW" NUMBER(1,0) DEFAULT 0, 
	"LSRULEMETSW" NUMBER(1,0) DEFAULT 0, 
	"ORDERID" NUMBER(*,0) DEFAULT 0, 
	"ORDEROPTSEQNUM" NUMBER(*,0) DEFAULT 0, 
	"MAXCAPACITYEXCEEDEDSW" NUMBER(1,0) DEFAULT 0, 
	"GROUPORDERID" NUMBER(*,0) DEFAULT 0
   ) 

   COMMENT ON COLUMN "SCPOMGR"."VEHICLELOAD"."ORDEROPTSEQNUM" IS 'Vehicle Load Sequence Number to obtain a nice sort and ease processing.'
   COMMENT ON COLUMN "SCPOMGR"."VEHICLELOAD"."MAXCAPACITYEXCEEDEDSW" IS 'Switch to indicate if the vehicle load is over capacity.'
