--------------------------------------------------------
--  Constraints for Table VEHICLELOAD
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."VEHICLELOAD" ADD CONSTRAINT "BOOL_VEHICLELOAD_APPROVSTATUS" CHECK (APPROVALSTATUS IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" ADD CONSTRAINT "BOOL_VEHICLELOAD_EXPORTED" CHECK (EXPORTED IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" ADD CONSTRAINT "BOOL_VEHICLELOAD_UPDATED" CHECK (UPDATED IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" ADD CONSTRAINT "BOOL_VEHILOAD_LOADSW" CHECK (LOADSW IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" ADD CONSTRAINT "BOOL_VEHILOAD_VENDORMINMETSW" CHECK (VENDORMINMETSW IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" ADD CONSTRAINT "BOOL_VEHILOAD_TRANMODMINMETSW" CHECK (TRANSMODEMINMETSW IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" ADD CONSTRAINT "BOOL_VEHILOAD_TOLERANCAPMETSW" CHECK (TOLERANCECAPMETSW IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" ADD CONSTRAINT "BOOL_VEHILOAD_LANEGRPMINMETSW" CHECK (LANEGROUPMINMETSW IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" ADD CONSTRAINT "BOOL_VEHILOAD_MAXCAPACTYMETSW" CHECK (MAXCAPACITYMETSW IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" ADD CONSTRAINT "BOOL_VEHILOAD_LSRULEMETSW" CHECK (LSRULEMETSW IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" ADD CONSTRAINT "VEHICLELOAD_PK" PRIMARY KEY ("LOADID")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("GROUPORDERID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("MAXCAPACITYEXCEEDEDSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("ORDEROPTSEQNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("ORDERID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("LSRULEMETSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("MAXCAPACITYMETSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("LANEGROUPID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("CONSOLIDATEDLOADSEQNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("LANEGROUPMINMETSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("TOLERANCECAPMETSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("TRANSMODEMINMETSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("VENDORMINMETSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("LOADSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("STATUSDESCR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("TRANSMODE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("LBSOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("UPDATED" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("EXPORTED" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("APPROVALSTATUS" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("STATUSDESC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("LBSTATUS" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("DESTSTATUS" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("SOURCESTATUS" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("ARRIVDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("SHIPDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("DESCR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOAD" MODIFY ("LOADID" NOT NULL ENABLE)
