--------------------------------------------------------
--  Constraints for Table VEHICLELOADTOTAL
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."VEHICLELOADTOTAL" ADD CONSTRAINT "XPKVEHICLELOADTOTAL" PRIMARY KEY ("LOADID", "ORDERID", "UOM")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."VEHICLELOADTOTAL" MODIFY ("UOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOADTOTAL" MODIFY ("LOADID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOADTOTAL" MODIFY ("QTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."VEHICLELOADTOTAL" MODIFY ("ORDERID" NOT NULL ENABLE)
